import { z } from "zod";

import { matchingService } from "@/server/matching/service";
import { recommendMatchesSchema } from "@/server/matching/schemas";
import {
  createPromptPacketSchema,
  saveSelfDiscoveryReportSchema,
} from "@/server/self-discovery/schemas";
import { selfDiscoveryService } from "@/server/self-discovery/service";
import { sendMessageSchema } from "@/server/social/schemas";
import { socialService } from "@/server/social/service";
import { validateInput } from "@/server/validation";
import { AppError } from "@/server/errors";

type ToolDefinition = {
  name: string;
  title: string;
  description: string;
  inputSchema: Record<string, unknown>;
  execute(input: unknown): Promise<unknown> | unknown;
};

const reportTypeEnum = [
  "personality_analysis",
  "dating_blueprint",
  "relationship_strengths",
  "blind_spots",
  "communication_style",
  "love_language",
  "attachment_style",
  "coaching_tools",
] as const;

const jsonObjectSchema: Record<string, unknown> = {
  type: "object",
  additionalProperties: true,
};

export const mcpTools: ToolDefinition[] = [
  {
    name: "get_report_types",
    title: "Get report types",
    description:
      "List self-discovery report types, prompt keys, and output schemas supported by Compatibility AI.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
    execute() {
      return selfDiscoveryService.listReportTypes();
    },
  },
  {
    name: "create_prompt_packet",
    title: "Create prompt packet",
    description:
      "Create the exact prompt and JSON schema packet a user can run in ChatGPT for a self-discovery report.",
    inputSchema: {
      type: "object",
      properties: {
        reportType: {
          type: "string",
          enum: reportTypeEnum,
        },
        userContext: {
          type: "string",
          minLength: 20,
          maxLength: 20000,
        },
      },
      required: ["reportType", "userContext"],
      additionalProperties: false,
    },
    execute(input) {
      return selfDiscoveryService.createPromptPacket(
        validateInput(createPromptPacketSchema, input),
      );
    },
  },
  {
    name: "save_report",
    title: "Save report",
    description:
      "Save a structured self-discovery report generated by ChatGPT into Compatibility AI.",
    inputSchema: {
      type: "object",
      properties: {
        userId: { type: "string", minLength: 1 },
        profileId: { type: "string", minLength: 1 },
        relationshipContextId: { type: "string", minLength: 1 },
        reportType: {
          type: "string",
          enum: reportTypeEnum,
        },
        chatgptOutput: {
          type: "object",
          properties: {
            reportType: { type: "string", minLength: 1 },
            title: { type: "string", minLength: 1, maxLength: 160 },
            summary: { type: "string", minLength: 1, maxLength: 3000 },
            sections: {
              type: "array",
              minItems: 1,
              items: {
                type: "object",
                properties: {
                  heading: { type: "string", minLength: 1, maxLength: 160 },
                  body: { type: "string", minLength: 1, maxLength: 3000 },
                },
                required: ["heading", "body"],
                additionalProperties: false,
              },
            },
            insights: {
              type: "array",
              items: { type: "string", minLength: 1, maxLength: 1000 },
            },
            actionItems: {
              type: "array",
              items: { type: "string", minLength: 1, maxLength: 1000 },
            },
            profileUpdates: jsonObjectSchema,
            confidence: { type: "number", minimum: 0, maximum: 1 },
          },
          required: [
            "reportType",
            "title",
            "summary",
            "sections",
            "confidence",
          ],
          additionalProperties: false,
        },
        shareable: { type: "boolean", default: true },
      },
      required: ["userId", "reportType", "chatgptOutput"],
      additionalProperties: false,
    },
    execute(input) {
      return selfDiscoveryService.saveReport(
        validateInput(saveSelfDiscoveryReportSchema, input),
      );
    },
  },
  {
    name: "get_recommendations",
    title: "Get recommendations",
    description:
      "Run the deterministic compatibility engine and return ranked match recommendations.",
    inputSchema: {
      type: "object",
      properties: {
        actorUserId: { type: "string", minLength: 1 },
        actorProfileId: { type: "string", minLength: 1 },
        relationshipContextId: { type: "string", minLength: 1 },
        candidateUserIds: {
          type: "array",
          maxItems: 500,
          items: { type: "string", minLength: 1 },
        },
        candidateProfileIds: {
          type: "array",
          maxItems: 500,
          items: { type: "string", minLength: 1 },
        },
        limit: { type: "integer", minimum: 1, maximum: 100, default: 25 },
        includeLimitedProfiles: { type: "boolean", default: false },
        minimumFinalScore: {
          type: "number",
          minimum: 0,
          maximum: 100,
          default: 0,
        },
        persistMatches: { type: "boolean", default: true },
        weights: {
          type: "object",
          properties: {
            lifestyle: { type: "number", minimum: 0 },
            personality: { type: "number", minimum: 0 },
            interests: { type: "number", minimum: 0 },
            values: { type: "number", minimum: 0 },
            vector: { type: "number", minimum: 0 },
          },
          additionalProperties: false,
        },
      },
      required: ["actorUserId"],
      additionalProperties: false,
    },
    execute(input) {
      return matchingService.recommendMatches(
        validateInput(recommendMatchesSchema, input),
      );
    },
  },
  {
    name: "send_message",
    title: "Send message",
    description:
      "Send a social message through an existing or newly created Compatibility AI conversation.",
    inputSchema: {
      type: "object",
      properties: {
        senderUserId: { type: "string", minLength: 1 },
        recipientUserId: { type: "string", minLength: 1 },
        conversationId: { type: "string", minLength: 1 },
        profileId: { type: "string", minLength: 1 },
        relationshipContextId: { type: "string", minLength: 1 },
        matchId: { type: "string", minLength: 1 },
        content: { type: "string", minLength: 1, maxLength: 4000 },
        metadata: jsonObjectSchema,
      },
      required: ["senderUserId", "recipientUserId", "content"],
      additionalProperties: false,
    },
    execute(input) {
      return socialService.sendMessage(validateInput(sendMessageSchema, input));
    },
  },
];

const callToolParamsSchema = z.object({
  name: z.string().min(1),
  arguments: z.unknown().optional(),
});

export function listTools() {
  return {
    tools: mcpTools.map(({ name, title, description, inputSchema }) => ({
      name,
      title,
      description,
      inputSchema,
    })),
  };
}

export async function callTool(params: unknown) {
  const input = validateInput(callToolParamsSchema, params);
  const tool = mcpTools.find((candidate) => candidate.name === input.name);

  if (!tool) {
    throw new AppError("NOT_FOUND", `Unknown MCP tool: ${input.name}`);
  }

  const structuredContent = await tool.execute(input.arguments ?? {});

  return {
    content: [
      {
        type: "text",
        text: JSON.stringify(structuredContent, null, 2),
      },
    ],
    structuredContent,
  };
}
